more descriptive error messages
Without this I was just getting generic errors like this (cause it
wasn't abel to split):

```
TypeError: Cannot read properties of undefined (reading 'utils')
```